### ISSUE TITLE
possibility of istioProxy sidecar instead of Envoyproxy

### ISSUE THREAD

**Issue by vchauhan1** [guicassolato/authorino-spicedb#1]
Hi @guicassolato, Instead of using an EnvoyProxy, Is there a possibility or integration possible to use it with Istio-proxy/sidecar?

It will amazing, to have some documentation for the same if possible

**Comment by guicassolato** [comment]
Hi @vchauhan1. I'll see if I can craft something for you. It may take a while since I'm focused on helping [Kuadrant](https://kuadrant.io) to go v1.0-ish.

Something for you to try in the meantime.

After you deploy Authorino, you have to register it as an extension provider in the mesh config. Something like:

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istiocontrolplane
  namespace: istio-system
spec:
  components: {…}
  meshConfig: # <=== add this
    extensionProviders:
    - envoyExtAuthzGrpc:
        port: 50051
        service: authorino-authorino-authorization.authorino.svc.cluster.local
      name: authorino
  …
```

Then you create an Istio `AuthorizationPolicy` CR with `action: CUSTOM`. E.g.:

```yaml
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: my-istio-authpolicy
  namespace: my-namespace
spec:
  action: CUSTOM
  provider:
    name: authorino
  rules:
  - to:
    - operation:
        hosts:
        - api.acme.com
        paths:
        - /admin*
  selector:
    matchLabels: # <=== replace this with something that matches the labels of the envoy sidecar proxy in the same namespace
      app: istio-ingressgateway
      istio: ingressgateway
```

I think [Open Data Hub](https://opendatahub.io/) is doing that for its integration with [Maistra](https://maistra.io/) (aka Istio for OpenShift): https://github.com/opendatahub-io/odh-manifests/tree/service-mesh-integration. It sets Authorino as the authorization provider.

The fact that the AuthConfig here is for integrating with a SpiceDB server won't matter much really.

If you want to peek on what Kuadrant does when one creates a Kuadrant `AuthPolicy` custom resource, you can run any of its guides for auth, such as this one: https://docs.kuadrant.io/kuadrant-operator/doc/user-guides/auth-for-app-devs-and-platform-engineers.

Then check out the resources it creates under the hood – i.e., Istio's `IstioOperator` and `AuthorizationPolicy`, and Authorino `AuthConfig`.

You'll see Kuadrant patches the `IstioOperator` and creates the `AuthorizationPolicy` similarly to what I exemplified above. The core spec of the `AuthPolicy` is turned into an Authorino `AuthConfig` (hostnames inherited from the Gateway API network resource.)
